profile: iterate
ceip_policy_disclosed: true # Installation fails if this is set to 'false'
excluded_packages: #list of packages that were previously installed from TKG repository that might create conflicts when installing TAP packages
- contour.tanzu.vmware.com
- cert-manager.tanzu.vmware.com

buildservice:
  kp_default_repository: "harbor-repo.vmware.com/jairotest/repo/1.3/build-service"
  kp_default_repository_username: "jairop"
  kp_default_repository_password: '*************'
  tanzunet_username: "jpastrana@pivotal.io"
  tanzunet_password: "************"
  enable_automatic_dependency_updates: false

supply_chain: basic

ootb_supply_chain_basic:
  registry:
    server: "harbor-repo.vmware.com"
    repository: "jairotest/repo/1.3/supply-chain"
  gitops:
    ssh_secret: ""

metadata_store:
  app_service_type: LoadBalancer # (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer

contour:
  envoy:
    service:
      type: LoadBalancer

cnrs:
  domain_name: "example.com"
